### ISSUE TITLE
Inconsistent Styling of Restore Button

### ISSUE THREAD

**Issue by Eric-Jackson** [mybb/mybb#3412]
I'm not sure if this is pre-existing, or introduced in 1.8.18, but the restore button does not share the same styling as other postbit buttons.

The styling is being overwritten by a `display: inline!important;` style.

![screen shot 2018-08-23 at 12 33 17 pm](https://user-images.githubusercontent.com/1268260/44538974-e0386200-a6d0-11e8-8f7a-b6a2c0303c64.png)

![screen shot 2018-08-23 at 12 25 54 pm](https://user-images.githubusercontent.com/1268260/44538980-e4fd1600-a6d0-11e8-8795-5650bdef7aae.png)

**Comment by Eric-Jackson** [comment]
This selector isn't needed at all. I believe the following CSS:

```css
.post:not(.deleted_post) .postbit_qrestore,
.post:not(.deleted_post) .status_type,
.post.deleted_post .postbit_mirage {
    display: none;
}
```

can replace what is proposed here:

https://github.com/mybb/mybb/pull/3216#issuecomment-412369569
